version: '3'
services:
  namenode:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: namenode
    hostname: namenode
    ports:
      - "50070:50070"
    volumes:
      - /data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hadoop
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    command: /etc/bootstrap.sh -d namenode

  datanode:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: datanode
    hostname: datanode
    ports:
      - "50075:50075"
    volumes:
      - /data/datanode:/hadoop/dfs/data
    environment:
      - CLUSTER_NAME=hadoop
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
      - HDFS_CONF_dfs_datanode_port=50075
    command: /etc/bootstrap.sh -d datanode
